"""
Abstract base strategy class defining the interface for all trading strategies.
All strategy implementations must inherit from this class and implement required methods.
"""

import copy
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
from uuid import uuid4

from loguru import logger

from core.config.settings import settings
from infrastructure.exchange.base_exchange import OHLCV
from services.market_data_engine import CandleBuffer
from services.market_data.snapshot import MarketSnapshot


class SignalType(Enum):
    """Types of trading signals."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"


class SignalStrength(Enum):
    """Signal confidence level."""

    LOW = 1
    MEDIUM = 2
    HIGH = 3
    VERY_HIGH = 4
    EXTREME = 5


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    signal_id: str = field(default_factory=lambda: str(uuid4()))
    strategy_name: str = ""
    symbol: str = ""
    timeframe: str = ""
    signal_type: SignalType = SignalType.HOLD
    signal_strength: SignalStrength = SignalStrength.LOW
    entry_price: float = 0.0
    stop_loss_price: Optional[float] = None
    take_profit_prices: List[Dict[str, float]] = field(default_factory=list)
    position_size_usdt: float = 0.0
    reason: str = ""
    indicators: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    validated: bool = False
    risk_approved: bool = False
    snapshot: Optional[MarketSnapshot] = None

    def __post_init__(self):
        """Validate required fields after initialization."""
        if not self.symbol:
            raise ValueError("Signal.symbol is required")
        if not self.timeframe:
            raise ValueError("Signal.timeframe is required")
        if self.entry_price <= 0:
            raise ValueError("Signal.entry_price must be positive")
        if self.signal_type == SignalType.HOLD:
            raise ValueError("Signal.signal_type cannot be HOLD")


@dataclass
class StrategyConfig:
    """Base configuration for all strategies."""

    name: str
    enabled: bool = True
    symbols: List[str] = field(default_factory=list)
    timeframes: List[str] = field(default_factory=list)
    min_confidence: SignalStrength = SignalStrength.MEDIUM
    max_positions: int = 5
    cooldown_minutes: int = None  # Will use settings.cooldown_minutes if None


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    Defines the interface that strategy engine expects from all strategies.
    """

    def __init__(self, config: StrategyConfig):
        self.config = config
        self.indicators: Dict[str, Dict[str, Any]] = {}  # symbol -> {indicator: value}
        # [PHASE 11] SHADOW BUFFER ELIMINATED: Strategies must rely entirely on MarketDataEngine
        logger.info(f"Strategy {self.config.name} initialized")

    @abstractmethod
    async def generate_signal(self, symbol: str, timeframe: str) -> Optional[Signal]:
        """
        Generate a trading signal based on current market data.
        This is the main strategy logic that analyzes data and produces signals.
        """
        pass

    @abstractmethod
    async def validate_signal(self, signal: Signal) -> bool:
        """
        Validate that a signal meets all strategy criteria before sending to risk engine.
        Performs additional checks to filter out false positives.
        """
        pass

    @abstractmethod
    async def filters(self, symbol: str, timeframe: str) -> bool:
        """
        Apply pre-analysis filters to determine if the symbol/timeframe should even be analyzed.
        Can be used for liquidity checks, volatility filters, etc.
        """
        pass

    @abstractmethod
    async def build_trade_plan(self, signal: Signal) -> Signal:
        """
        Build complete trade plan from a raw signal including position sizing, TP/SL levels.
        Enhances the basic signal with execution parameters.
        """
        pass

    async def update_candle_data(self, symbol: str, timeframe: str, candles: List[OHLCV]) -> None:
        # DEPRECATED — strategies fetch candles exclusively from MarketDataEngine
        pass

    def get_candles(self, symbol: str, timeframe: str, limit: int = 100) -> List[OHLCV]:
        """Get recent candles for analysis — prefer atomic snapshot from StrategyEngine."""
        from core.container import container
        try:
            se = container.get("strategy_engine")
            if se and hasattr(se, "_analysis_snapshots"):
                snap = se._analysis_snapshots.get((symbol, timeframe))
                if snap:
                    return list(snap)[-limit:]
        except Exception as e:
            logger.exception(
                f"[GET_CANDLES_ERROR] "
                f"{symbol}/{timeframe}: {e}"
            )

        try:
            mde = container.get("market_data_engine")
            import inspect, asyncio

            if inspect.isawaitable(mde) or asyncio.iscoroutine(mde):
                logger.critical("[ARCHITECTURE VIOLATION] MDE is awaitable, cannot fetch candles safely!")
                return []
            elif mde:
                snapshot = mde.get_candles_snapshot(symbol, timeframe, limit)
                if snapshot:
                    return snapshot
        except Exception as e:
            logger.error(f"Failed to get candles from MDE for {symbol} {timeframe}: {e}")

        return []

    async def is_in_cooldown(self, symbol: str, timeframe: str) -> bool:
        """Override in subclass or via SignalSafetyMixin."""
        return False

    async def record_signal(self, symbol: str, timeframe: str) -> None:
        """Override in subclass or via SignalSafetyMixin."""
        pass

    async def on_indicators_updated(self, event: Any) -> None:
        """Handler cho event market.indicators_updated từ Market Data Engine."""
        data = event.data
        symbol = data["symbol"]
        timeframe = data["timeframe"]
        indicators = data["indicators"]

        # Chỉ xử lý nếu strategy này theo dõi symbol và timeframe này
        if symbol in self.config.symbols and timeframe in self.config.timeframes:
            if symbol not in self.indicators:
                self.indicators[symbol] = {}
            self.indicators[symbol][timeframe] = indicators
            logger.debug(
                f"Updated indicators for {symbol} {timeframe} in strategy {self.config.name}"
            )

            # Tự động trigger signal generation sau khi cập nhật indicators
            # This will be called by strategy engine, or we can trigger async
            # await self.generate_signal(symbol, timeframe)

    async def calculate_indicators(self, symbol: str, timeframe: str) -> Optional[MarketSnapshot]:
        """
        Get indicators as MarketSnapshot for snapshot consistency.
        
        Returns:
            MarketSnapshot if available, None otherwise
        """
        bundle_key = (symbol, timeframe)
        from core.container import container
        import time
        try:
            se = container.get("strategy_engine")
            if se and hasattr(se, "_indicator_snapshots"):
                # [RACE-PROOF] Log cache read with microsecond timestamp
                cache_read_timestamp_us = time.time()
                
                # [FIX CACHE RACE CONDITION] ONLY retrieve timestamp-keyed cache to prevent overwrites
                # First try to get the latest timestamp from the regular cache
                cached = se._indicator_snapshots.get(bundle_key)
                cache_object_id = id(cached) if cached else None
                
                if cached:
                    signal_candle_ts = cached.get("signal_candle_ts", 0)
                    cached_crossover = cached.get("crossover_detected", "NOT FOUND")
                    logger.debug(f"[RACE-PROOF] CACHE READ (regular): ts_us={cache_read_timestamp_us:.6f}, key={bundle_key}, signal_candle_ts={signal_candle_ts}, crossover={cached_crossover}, object_id={cache_object_id}")
                    
                    if signal_candle_ts > 0:
                        timestamp_key = (symbol, timeframe, signal_candle_ts)
                        timestamp_cached = se._indicator_snapshots.get(timestamp_key)
                        timestamp_object_id = id(timestamp_cached) if timestamp_cached else None
                        timestamp_crossover = timestamp_cached.get("crossover_detected", "NOT FOUND") if timestamp_cached else "NOT FOUND"
                        logger.debug(f"[RACE-PROOF] CACHE READ (timestamp-keyed): ts_us={cache_read_timestamp_us:.6f}, key={timestamp_key}, exists={timestamp_cached is not None}, crossover={timestamp_crossover}, object_id={timestamp_object_id}")
                        
                        if timestamp_cached:
                            logger.debug(f"[RACE-PROOF] USING TIMESTAMP-KEYED CACHE: ts_us={cache_read_timestamp_us:.6f}, crossover={timestamp_crossover}")
                            cached = timestamp_cached
                    
                    # Create snapshot from cached indicators
                    if isinstance(cached, MarketSnapshot):
                        return cached
                    elif isinstance(cached, dict):
                        # Create a MarketSnapshot from dict (temporary solution)
                        # Calculate dynamic reference_candle_index based on timeframe's confirmation candles
                        # SUPPORT BOTH MODES: 0=Realtime (forming candle, -1), >=1=Confirmation (closed candle, -2)
                        timeframe_confirmation_map = {
                            "5m": settings.confirmation_candles_5m,
                            "15m": settings.confirmation_candles_15m,
                            "1H": settings.confirmation_candles_1h,
                            "4H": settings.confirmation_candles_4h,
                            "1D": settings.confirmation_candles_1d,
                            "1W": settings.confirmation_candles_1w,
                            "1M": settings.confirmation_candles_1m,
                        }
                        if timeframe not in timeframe_confirmation_map:
                            logger.error(f"UNKNOWN_TIMEFRAME: {timeframe}")
                            raise RuntimeError(f"UNKNOWN_TIMEFRAME: {timeframe}")
                        confirm_candles = timeframe_confirmation_map[timeframe]
                        ref_index = -2 if confirm_candles >= 1 else -1
                        candle_type = "closed" if confirm_candles >= 1 else "forming"
                        # Create snapshot - all values pre-validated by MarketDataEngine signal gate
                        # PRODUCTION HARD RULES are enforced centrally in MarketSnapshot.create()
                        snapshot = MarketSnapshot.create(
                            symbol=symbol,
                            timeframe=timeframe,
                            reference_candle_timestamp=cached.get("signal_candle_ts", 0),
                            reference_candle_index=ref_index,
                            candle_type=candle_type,
                            ema_fast=cached.get("ema9", 0.0),
                            ema_slow=cached.get("ema21", 0.0),
                            adx=cached.get("adx", 0.0),
                            body_pct=cached.get("body_pct", 0.0),
                            indicators=copy.deepcopy(cached),  # SHARED REFERENCE ELIMINATION: Deep copy to prevent mutation
                            raw_data={
                                "close": cached.get("close", 0.0),
                                "open": cached.get("open", 0.0),
                                "high": cached.get("high", 0.0),
                                "low": cached.get("low", 0.0),
                                "volume": cached.get("volume", 0.0),
                            },  # Extract OHLCV from cached indicators for entry price
                        )
                        # Redundant safety check - will never fail in normal operation
                        snapshot.validate_consistency()
                        logger.info(
                            f"[SNAPSHOT-VALID] Strategy layer cache snapshot created for {symbol}/{timeframe}: "
                            f"candle_type={snapshot.candle_type}, ref_index={snapshot.reference_candle_index}"
                        )
                        # --- End of snapshot creation ---
                        logger.debug(
                            f"[MUTATION-CACHE-READ] id(cached)={id(cached)}, "
                            f"cached['body_pct']={cached.get('body_pct', 'NOT_SET')}, "
                            f"snapshot.body_pct={snapshot.body_pct}, "
                            f"id(snapshot.indicators)={id(snapshot.indicators)}, "
                            f"SHARED_REFERENCE={'YES' if id(cached) == id(snapshot.indicators) else 'NO'}"
                        )
                        # --- RUNTIME VALIDATION: Ensure snapshot consistency per 4_chien_luoc.md v1.2 ---
                        if not snapshot.validate_consistency():
                            logger.error(
                                f"[STRATEGY-COMPLIANCE] Snapshot consistency validation FAILED for {symbol}/{timeframe}: "
                                f"candle_type={snapshot.candle_type}, ref_index={snapshot.reference_candle_index}"
                            )
                        return snapshot
        except Exception as e:
            logger.exception(
                f"[BASE_STRATEGY_CACHED_BRANCH_ERROR] "
                f"{symbol}/{timeframe}: {e}"
            )

        try:
            mde = container.get("market_data_engine")
            import inspect, asyncio

            if inspect.isawaitable(mde) or asyncio.iscoroutine(mde):
                logger.debug("MDE instance is awaitable/coroutine; falling back to local indicators")
            elif mde:
                # MDE.get_indicators returns Dict for backward compatibility
                # We need to convert to MarketSnapshot
                indicators = mde.get_indicators(symbol, timeframe)
                if indicators:
                    # SUPPORT BOTH MODES: 0=Realtime (forming candle, -1), >=1=Confirmation (closed candle, -2)
                    timeframe_confirmation_map = {
                        "5m": settings.confirmation_candles_5m,
                        "15m": settings.confirmation_candles_15m,
                        "1H": settings.confirmation_candles_1h,
                        "4H": settings.confirmation_candles_4h,
                        "1D": settings.confirmation_candles_1d,
                        "1W": settings.confirmation_candles_1w,
                        "1M": settings.confirmation_candles_1m,
                    }
                    if timeframe not in timeframe_confirmation_map:
                        logger.error(f"UNKNOWN_TIMEFRAME: {timeframe}")
                        raise RuntimeError(f"UNKNOWN_TIMEFRAME: {timeframe}")
                    confirm_candles = timeframe_confirmation_map[timeframe]
                    # Create snapshot - all values pre-validated by MarketDataEngine signal gate
                    # PRODUCTION HARD RULES are enforced centrally in MarketSnapshot.create()
                    # Use per-timeframe confirmation settings from configuration
                    confirm_candles = timeframe_confirmation_map[timeframe]
                    ref_index = -2 if confirm_candles >= 1 else -1
                    candle_type = "closed" if confirm_candles >=1 else "forming"
                    snapshot = MarketSnapshot.create(
                        symbol=symbol,
                        timeframe=timeframe,
                        reference_candle_timestamp=indicators.get("signal_candle_ts", 0),
                        reference_candle_index=ref_index,
                        candle_type=candle_type,
                        ema_fast=indicators.get("ema9", 0.0),
                        ema_slow=indicators.get("ema21", 0.0),
                        adx=indicators.get("adx", 0.0),
                        body_pct=indicators.get("body_pct", 0.0),
                        indicators=indicators,
                    )
                    # Redundant safety check - will never fail in normal operation
                    snapshot.validate_consistency()
                    logger.info(
                        f"[SNAPSHOT-VALID] Strategy layer snapshot created for {symbol}/{timeframe}: "
                        f"candle_type={snapshot.candle_type}, ref_index={snapshot.reference_candle_index}"
                        )
                    return snapshot
        except Exception as e:
            logger.error(f"Failed to get indicators from MDE for {symbol} {timeframe}: {e}")

        return None

    async def get_market_snapshot(self, symbol: str, timeframe: str) -> Optional[MarketSnapshot]:
        """Asynchronous wrapper for calculate_indicators, primarily for testing and timeframe validation."""
        from services.market_data_engine import MarketDataEngine
        if timeframe not in MarketDataEngine.TIMEFRAME_SECONDS:
            logger.error(f"UNKNOWN_TIMEFRAME: {timeframe}")
            raise RuntimeError(f"UNKNOWN_TIMEFRAME: {timeframe}")
        return await self.calculate_indicators(symbol, timeframe)

    def can_accept_more_positions(self) -> bool:
        """Check if strategy can take on more positions based on max_positions config."""
        # This will be checked by the strategy engine against actual open positions
        return True